pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r index.html jewelry_cards ic font konacard.svg image_*.png mov.mp4 public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
